from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


class RiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class VitalSign(BaseModel):
    timestamp: datetime
    heart_rate: Optional[float] = None
    systolic_bp: Optional[float] = None
    diastolic_bp: Optional[float] = None
    respiratory_rate: Optional[float] = None
    temperature: Optional[float] = None  # Celsius
    spo2: Optional[float] = None
    gcs: Optional[int] = None  # Glasgow Coma Scale (3-15)


class LabResult(BaseModel):
    timestamp: datetime
    test_name: str
    value: float
    unit: str
    normal_range_low: Optional[float] = None
    normal_range_high: Optional[float] = None
    is_abnormal: bool = False
    is_critical: bool = False


class ClinicalNote(BaseModel):
    timestamp: datetime
    author: str  # e.g., "Dr. Smith - Attending"
    note_type: str  # e.g., "Progress Note", "Nursing Note"
    text: str
    shift: Optional[str] = None  # "Day", "Night"


class SOFAScore(BaseModel):
    timestamp: datetime
    respiration: int = Field(ge=0, le=4)
    coagulation: int = Field(ge=0, le=4)
    liver: int = Field(ge=0, le=4)
    cardiovascular: int = Field(ge=0, le=4)
    cns: int = Field(ge=0, le=4)
    renal: int = Field(ge=0, le=4)
    total: int = Field(ge=0, le=24)


class QSOFAScore(BaseModel):
    timestamp: datetime
    low_bp: bool = False  # SBP <= 100 mmHg
    high_rr: bool = False  # RR >= 22
    altered_mentation: bool = False  # GCS < 15
    total: int = Field(ge=0, le=3)


class PatientData(BaseModel):
    patient_id: str
    age: Optional[int] = None
    gender: Optional[str] = None
    admission_date: datetime
    diagnosis_on_admission: Optional[str] = None
    vitals: list[VitalSign] = []
    labs: list[LabResult] = []
    notes: list[ClinicalNote] = []
    sofa_scores: list[SOFAScore] = []
    qsofa_scores: list[QSOFAScore] = []


class TimelineEvent(BaseModel):
    timestamp: datetime
    event_type: str  # "vital", "lab", "note", "score", "alert"
    category: str
    description: str
    value: Optional[str] = None
    severity: Optional[RiskLevel] = None
    source: Optional[str] = None


class OutlierFlag(BaseModel):
    timestamp: datetime
    lab_name: str
    flagged_value: float
    expected_range: str
    z_score: float
    recommendation: str = "Recommend redraw to confirm before updating diagnosis"


class GuidelineCitation(BaseModel):
    guideline_name: str
    section: str
    text: str
    relevance_score: float
    source_document: str


class RiskFlag(BaseModel):
    condition: str
    risk_level: RiskLevel
    evidence: list[str]
    guideline_citations: list[GuidelineCitation]
    recommended_actions: list[str]
    confidence: float


class DiagnosticRiskReport(BaseModel):
    patient_id: str
    generated_at: datetime
    summary: str
    risk_flags: list[RiskFlag]
    sofa_score: Optional[SOFAScore] = None
    qsofa_score: Optional[QSOFAScore] = None
    timeline: list[TimelineEvent]
    outlier_flags: list[OutlierFlag]
    disease_progression: str
    safety_caveat: str = (
        "DECISION-SUPPORT ONLY: This report is generated by an AI system and is intended "
        "solely as a clinical decision-support tool. It does NOT constitute a medical diagnosis. "
        "All outputs must be reviewed and validated by a qualified clinician before any clinical "
        "action is taken. The system may contain errors and should never replace professional "
        "medical judgment."
    )


class ShiftHandoffReport(BaseModel):
    patient_id: str
    generated_at: datetime
    outgoing_shift: str
    incoming_shift: str
    patient_summary: str
    active_problems: list[str]
    critical_alerts: list[str]
    recent_changes: list[str]
    pending_actions: list[str]
    current_medications_notes: str
    risk_assessment: str
    sofa_trend: str
    safety_caveat: str = (
        "AI-GENERATED HANDOFF AID: This summary is auto-generated to assist shift transitions. "
        "It must be verified against the patient chart by the incoming clinician."
    )
