"""
Chief Synthesis Agent – integrates all agent outputs into a final Diagnostic Risk Report.

Combines note parsing, temporal mapping, and guideline RAG outputs into a
unified, actionable clinical decision-support report with safety caveats.

Includes:
- Lab outlier detection with diagnosis-hold logic (Twist 2)
- Family-friendly compassionate summary generation (Twist 1)
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Optional

import numpy as np
import pandas as pd
import google.generativeai as genai

from backend.config import GEMINI_API_KEY, GEMINI_MODEL, LLM_TEMPERATURE, OUTLIER_Z_THRESHOLD
from backend.utils.outlier_detector import detect_outlier, format_outlier_alert

logger = logging.getLogger(__name__)

genai.configure(api_key=GEMINI_API_KEY)
_model = genai.GenerativeModel(GEMINI_MODEL)

_SAFETY_CAVEAT = (
    "DECISION-SUPPORT ONLY: This report is generated by an AI system and is intended "
    "solely as a clinical decision-support aid. It does NOT replace clinical judgment. "
    "All findings, scores, and recommendations must be verified by a qualified healthcare "
    "professional before any clinical action is taken. The system may produce inaccurate "
    "or incomplete results."
)

_HANDOFF_SAFETY_CAVEAT = (
    "AI-GENERATED HANDOFF AID: This shift handoff summary is generated by an AI system "
    "and should be used as a supplementary reference only. Verify all clinical details "
    "with primary documentation and direct assessment. Not a substitute for clinician-to-"
    "clinician handoff communication."
)

_DIAGNOSIS_HOLD_CAVEAT = (
    "DIAGNOSIS HOLD: One or more lab results have been flagged as statistical outliers "
    "that contradict the prior 72 hours of consistent data. The Chief Synthesis Agent has "
    "REFUSED to revise the current diagnosis based on these anomalous values. A confirmed "
    "redraw must be received before these values are incorporated into the clinical assessment."
)

_FAMILY_CAVEAT = (
    "FAMILY COMMUNICATION AID: This summary is AI-generated in simplified, compassionate "
    "language for family members. It is NOT a clinical document. All medical decisions must "
    "be discussed with the treating physician."
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def synthesize_report(
    note_parser_output: dict,
    temporal_output: dict,
    rag_output: dict,
    patient_info: dict,
    vitals_df: pd.DataFrame,
    labs_df: pd.DataFrame,
) -> dict:
    """Integrate all agent outputs into a final Diagnostic Risk Report.

    Parameters
    ----------
    note_parser_output : dict
        Output from ``note_parser.parse_all_notes`` or ``parse_clinical_note``.
    temporal_output : dict
        Should contain keys: timeline, scores, trends, disease_progression.
    rag_output : dict
        Should contain keys: recommendations, citations, evidence_level.
    patient_info : dict
        Patient demographics: patient_id, age, gender, admission_date, etc.
    vitals_df : DataFrame
        Columns: timestamp, parameter, value.
    labs_df : DataFrame
        Columns: timestamp, parameter, value.

    Returns
    -------
    dict – complete diagnostic risk report.
    """
    patient_id = patient_info.get("patient_id", "UNKNOWN")

    # Extract scores
    scores = temporal_output.get("scores", [])
    latest_sofa = {}
    latest_qsofa = {}
    if scores:
        latest = scores[-1]
        latest_sofa = {
            "total": latest.get("sofa_total", 0),
            "components": latest.get("sofa_components", {}),
        }
        latest_qsofa = {
            "total": latest.get("qsofa_total", 0),
            "components": latest.get("qsofa_components", {}),
        }

    # Extract trends
    trends = temporal_output.get("trends", [])
    timeline = temporal_output.get("timeline", [])
    disease_progression = temporal_output.get("disease_progression", "No progression data available.")

    # Detect lab outliers
    outlier_flags = detect_lab_outliers(labs_df)

    # ------------------------------------------------------------------
    # TWIST 2: Diagnosis Hold — detect contradictory results that clash
    # with 3 days of consistent data. If found, REFUSE to revise the
    # diagnosis based on the anomalous value. Filter out outlier-affected
    # labs from trend-based risk calculations.
    # ------------------------------------------------------------------
    diagnosis_hold = False
    diagnosis_hold_details: list[dict] = []
    outlier_lab_names = {o["lab_name"].lower() for o in outlier_flags}

    for outlier in outlier_flags:
        lab_name = outlier["lab_name"]
        z_score = outlier.get("z_score", 0)
        flagged_value = outlier.get("flagged_value")
        mean_val = outlier.get("mean", 0)

        # Check if this contradicts 3 days of consistent data
        consistency = _check_prior_consistency(labs_df, lab_name, window_days=3)

        if consistency["is_consistent"] and abs(z_score) >= OUTLIER_Z_THRESHOLD:
            diagnosis_hold = True
            diagnosis_hold_details.append({
                "lab_name": lab_name,
                "flagged_value": flagged_value,
                "z_score": z_score,
                "prior_mean": consistency["mean"],
                "prior_std": consistency["std"],
                "prior_count": consistency["count"],
                "prior_cv": consistency["cv"],
                "reason": (
                    f"{lab_name} value of {flagged_value} contradicts "
                    f"{consistency['count']} consistent readings over the prior "
                    f"72 hours (mean={consistency['mean']:.1f}, CV={consistency['cv']:.1%}). "
                    f"Z-score: {abs(z_score):.1f}. Probable mislabeled/erroneous result. "
                    f"Diagnosis NOT revised — awaiting confirmed redraw."
                ),
                "status": "AWAITING_REDRAW",
            })

    # Filter trends: exclude outlier-affected labs from risk calculation
    safe_trends = [
        t for t in trends
        if t.get("lab_name", "").lower() not in outlier_lab_names
    ]

    # ------------------------------------------------------------------
    # Data completeness check — detect when SOFA/qSOFA are artificially
    # low because critical lab parameters are missing (not genuinely normal).
    # ------------------------------------------------------------------
    sofa_total = latest_sofa.get("total", 0)
    qsofa_total = latest_qsofa.get("total", 0)
    sofa_components = latest_sofa.get("components", {})
    data_completeness = _assess_data_completeness(labs_df, vitals_df, sofa_components)

    # Determine overall risk level using SAFE trends only (outlier-excluded)
    risk_level = determine_risk_level(
        sofa_total, qsofa_total, safe_trends, len(outlier_flags),
        data_completeness=data_completeness,
        note_parser_output=note_parser_output,
        patient_info=patient_info,
    )

    # Build risk flags from conditions and evidence (using safe trends)
    risk_flags = _build_risk_flags(
        note_parser_output, temporal_output, rag_output,
        sofa_total, qsofa_total, safe_trends,
    )

    # If data is incomplete, add an explicit risk flag
    if data_completeness.get("is_incomplete", False):
        missing_list = data_completeness.get("missing_critical", [])
        risk_flags.insert(0, {
            "condition": "Insufficient Lab Data",
            "risk_level": "MODERATE",
            "evidence": [
                f"Missing critical labs: {', '.join(missing_list)}",
                f"Data completeness: {data_completeness.get('completeness_pct', 0):.0f}% of key parameters available",
                "SOFA score may underestimate severity due to missing organ-system data",
            ],
            "guideline_citations": [],
            "recommended_actions": [
                "Order missing lab panels immediately (CBC, BMP, LFTs, Lactate, Coagulation)",
                "Do NOT interpret low SOFA as 'stable' — data is insufficient for reliable scoring",
                "Perform bedside clinical assessment to supplement missing data",
            ],
            "confidence": 0.40,
        })

    # Generate executive summary
    summary = _generate_executive_summary(
        patient_info, risk_level, risk_flags, sofa_total, qsofa_total,
        disease_progression,
    )

    # If diagnosis is on hold, prepend hold notice to summary
    if diagnosis_hold:
        hold_labs = ", ".join(d["lab_name"] for d in diagnosis_hold_details)
        summary = (
            f"[DIAGNOSIS HOLD] Anomalous lab result(s) detected for: {hold_labs}. "
            f"These values contradict 72 hours of consistent data and are excluded "
            f"from the current assessment pending confirmed redraw. "
        ) + summary

    return {
        "patient_id": patient_id,
        "generated_at": datetime.now(),
        "summary": summary,
        "risk_level": risk_level,
        "risk_flags": risk_flags,
        "sofa_score": latest_sofa,
        "qsofa_score": latest_qsofa,
        "timeline": timeline,
        "outlier_flags": outlier_flags,
        "disease_progression": disease_progression,
        "diagnosis_hold": diagnosis_hold,
        "diagnosis_hold_details": diagnosis_hold_details,
        "data_completeness": data_completeness,
        "safety_caveat": _DIAGNOSIS_HOLD_CAVEAT if diagnosis_hold else _SAFETY_CAVEAT,
    }


def detect_lab_outliers(labs_df: pd.DataFrame) -> list[dict]:
    """Check each lab's latest value against its recent history for outliers.

    Parameters
    ----------
    labs_df : DataFrame
        Columns: timestamp, parameter, value.

    Returns
    -------
    list of dict – outlier flags with lab name and detection details.
    """
    if labs_df is None or labs_df.empty:
        return []

    # Determine column names — MIMIC uses "label" and "charttime", others may use "parameter" and "timestamp"
    param_col = "label" if "label" in labs_df.columns else "parameter" if "parameter" in labs_df.columns else None
    value_col = "valuenum" if "valuenum" in labs_df.columns else "value" if "value" in labs_df.columns else None
    time_col = "charttime" if "charttime" in labs_df.columns else "timestamp" if "timestamp" in labs_df.columns else None

    if param_col is None or value_col is None:
        return []

    outlier_flags: list[dict] = []
    parameters = labs_df[param_col].dropna().unique()

    for param in parameters:
        param_data = labs_df.loc[labs_df[param_col] == param].copy()
        param_data = param_data.dropna(subset=[value_col])
        if time_col and time_col in param_data.columns:
            param_data = param_data.sort_values(time_col)
        if len(param_data) < 3:
            continue

        values = param_data[value_col].astype(float).tolist()
        latest_value = values[-1]
        history = values[:-1]

        result = detect_outlier(history, latest_value, z_threshold=OUTLIER_Z_THRESHOLD)

        if result["is_outlier"]:
            alert_text = format_outlier_alert(
                {**result, "value": latest_value},
                param,
            )
            ts = param_data[time_col].iloc[-1] if time_col and time_col in param_data.columns else datetime.now()
            outlier_flags.append({
                "lab_name": param,
                "flagged_value": latest_value,
                "z_score": result["z_score"],
                "mean": result["mean"],
                "std": result["std"],
                "is_outlier": True,
                "alert": alert_text,
                "recommendation": result["recommendation"],
                "expected_range": f"{result['mean']:.1f} ± {result['std']:.1f}",
                "timestamp": ts,
            })

    return outlier_flags


def determine_risk_level(
    sofa_score: int,
    qsofa_score: int,
    trends: list[dict],
    outlier_count: int,
    *,
    data_completeness: Optional[dict] = None,
    note_parser_output: Optional[dict] = None,
    patient_info: Optional[dict] = None,
) -> str:
    """Determine the overall clinical risk level.

    Logic:
    - CRITICAL: SOFA >= 10, or SOFA >= 6 with rising lactate > 4
    - HIGH: SOFA >= 6, or qSOFA >= 2 with any concerning trend,
            or admission diagnosis is high-acuity with incomplete data
    - MODERATE: SOFA 2-5, or qSOFA >= 2, or any single concerning trend,
               or critical data is missing (preventing reliable scoring),
               or admission diagnosis suggests sepsis/organ failure
    - LOW: SOFA < 2 and qSOFA < 2 and no concerning trends and data is complete

    Parameters
    ----------
    sofa_score : int
    qsofa_score : int
    trends : list of dict
        Output from ``temporal_mapper.detect_all_trends``.
    outlier_count : int
        Number of detected lab outliers.
    data_completeness : dict, optional
        From ``_assess_data_completeness``.
    note_parser_output : dict, optional
        Output from Agent 1 — used to detect sepsis-related conditions.
    patient_info : dict, optional
        Patient demographics including admission diagnosis.

    Returns
    -------
    str – "LOW", "MODERATE", "HIGH", or "CRITICAL".
    """
    concerning_trends = [t for t in trends if t.get("is_concerning", False)]

    # Check for rising lactate > 4
    rising_lactate_critical = False
    for t in trends:
        if t.get("lab_name", "").lower() == "lactate" and t.get("trend") == "rising":
            values = t.get("values", [])
            if values:
                last_val = values[-1]
                if isinstance(last_val, dict):
                    last_val = last_val.get("value", 0)
                elif isinstance(last_val, (list, tuple)):
                    last_val = last_val[-1]
                if float(last_val) > 4.0:
                    rising_lactate_critical = True

    # CRITICAL
    if sofa_score >= 10:
        return "CRITICAL"
    if sofa_score >= 6 and rising_lactate_critical:
        return "CRITICAL"

    # HIGH
    if sofa_score >= 6:
        return "HIGH"
    if qsofa_score >= 2 and concerning_trends:
        return "HIGH"

    # MODERATE
    if 2 <= sofa_score <= 5:
        return "MODERATE"
    if qsofa_score >= 2:
        return "MODERATE"
    if concerning_trends:
        return "MODERATE"

    # ------------------------------------------------------------------
    # Safety net: if SOFA = 0 and data is INCOMPLETE, do NOT report LOW.
    # Missing data ≠ healthy. A sepsis patient with missing Creatinine,
    # Bilirubin, Lactate, Platelets will score SOFA=0 falsely.
    # ------------------------------------------------------------------
    is_data_incomplete = (
        data_completeness is not None
        and data_completeness.get("is_incomplete", False)
    )

    # Check if admission diagnosis or note-parsed conditions suggest
    # high-acuity pathology (sepsis, organ failure, shock, etc.)
    high_acuity_keywords = {
        "sepsis", "septic", "shock", "organ failure", "respiratory failure",
        "ards", "acute kidney", "aki", "pneumonia", "meningitis",
        "bacteremia", "endocarditis", "necrotizing", "peritonitis",
        "multi-organ", "mof", "dic",
    }

    has_high_acuity_diagnosis = False

    # Check admission diagnosis
    if patient_info:
        diag = str(patient_info.get("diagnosis", "")).lower()
        if any(kw in diag for kw in high_acuity_keywords):
            has_high_acuity_diagnosis = True

    # Check conditions extracted by Agent 1 (note parser)
    if not has_high_acuity_diagnosis and note_parser_output:
        aggregated = note_parser_output.get("aggregated", {})
        all_conditions = aggregated.get(
            "all_conditions",
            note_parser_output.get("all_conditions", []),
        )
        for cond in all_conditions:
            cond_str = cond.get("condition", cond) if isinstance(cond, dict) else str(cond)
            if any(kw in str(cond_str).lower() for kw in high_acuity_keywords):
                has_high_acuity_diagnosis = True
                break
        # Also check critical findings
        critical = aggregated.get(
            "critical_findings",
            note_parser_output.get("critical_findings", []),
        )
        for finding in critical:
            if any(kw in str(finding).lower() for kw in high_acuity_keywords):
                has_high_acuity_diagnosis = True
                break

    # If data is incomplete AND diagnosis suggests high-acuity → HIGH
    if is_data_incomplete and has_high_acuity_diagnosis:
        return "HIGH"

    # If data is incomplete (even without explicit high-acuity diagnosis) → MODERATE
    # Rationale: We cannot safely call a patient LOW risk if we lack the data to score them
    if is_data_incomplete:
        return "MODERATE"

    # If diagnosis is high-acuity but scores are genuinely zero with COMPLETE data → MODERATE
    # (The patient may be early in their course or improving)
    if has_high_acuity_diagnosis:
        return "MODERATE"

    # LOW — only when data is complete and scores are genuinely low
    return "LOW"


def generate_shift_handoff(
    report: dict,
    patient_info: dict,
    current_shift: str,
) -> dict:
    """Generate a shift handoff report from the diagnostic risk report.

    Parameters
    ----------
    report : dict
        Output from ``synthesize_report``.
    patient_info : dict
        Patient demographics and context.
    current_shift : str
        Current (outgoing) shift label, e.g. "Day", "Night", "Evening".

    Returns
    -------
    dict – structured shift handoff report.
    """
    patient_id = patient_info.get("patient_id", "UNKNOWN")

    # Determine incoming shift
    shift_sequence = {"Day": "Evening", "Evening": "Night", "Night": "Day"}
    incoming_shift = shift_sequence.get(current_shift, "Next")

    # Extract data from report
    risk_level = report.get("risk_level", "UNKNOWN")
    risk_flags = report.get("risk_flags", [])
    timeline = report.get("timeline", [])
    outlier_flags = report.get("outlier_flags", [])
    sofa_score = report.get("sofa_score", {})
    disease_progression = report.get("disease_progression", "")

    # Critical alerts
    critical_alerts: list[str] = []
    for flag in risk_flags:
        if flag.get("risk_level") in ("HIGH", "CRITICAL"):
            condition = flag.get("condition", "Unknown")
            evidence = flag.get("evidence", [])
            critical_alerts.append(
                f"{condition} ({flag['risk_level']}): {'; '.join(evidence[:3])}"
            )
    for outlier in outlier_flags:
        critical_alerts.append(outlier.get("alert", "Lab outlier detected"))

    # Recent changes (last 12 hours relative to latest timeline event, not wall clock)
    recent_changes: list[str] = []
    timeline_timestamps = [
        e["timestamp"] for e in timeline
        if isinstance(e.get("timestamp"), datetime)
    ]
    max_ts = max(timeline_timestamps) if timeline_timestamps else datetime.now()
    cutoff = max_ts - timedelta(hours=12)
    for event in timeline:
        ts = event.get("timestamp")
        if isinstance(ts, datetime) and ts >= cutoff:
            if event.get("severity") in ("warning", "critical") or event.get("event_type") == "alert":
                recent_changes.append(event.get("description", ""))

    # Pending actions from recommendations
    pending_actions: list[str] = []
    for flag in risk_flags:
        actions = flag.get("recommended_actions", [])
        pending_actions.extend(actions[:2])  # Top 2 per flag

    # Build SOFA trend string
    sofa_trend = _build_sofa_trend_string(report)

    # Medications/notes summary from risk flags
    medications_notes: list[str] = []
    for flag in risk_flags:
        evidence = flag.get("evidence", [])
        for e in evidence:
            if any(keyword in e.lower() for keyword in ["medication", "vasopressor", "antibiotic", "infusion"]):
                medications_notes.append(e)

    medications_notes_str = "; ".join(medications_notes) if medications_notes else "See medication administration record."

    # Generate natural language summary using Gemini
    patient_summary, active_problems = _generate_handoff_narrative(
        patient_info, risk_level, risk_flags, disease_progression, sofa_score,
    )

    return {
        "patient_id": patient_id,
        "generated_at": datetime.now(),
        "outgoing_shift": current_shift,
        "incoming_shift": incoming_shift,
        "patient_summary": patient_summary,
        "active_problems": active_problems,
        "critical_alerts": critical_alerts,
        "recent_changes": recent_changes,
        "pending_actions": pending_actions,
        "current_medications_notes": medications_notes_str,
        "risk_assessment": f"Overall risk: {risk_level}. {report.get('summary', '')}",
        "sofa_trend": sofa_trend,
        "safety_caveat": _HANDOFF_SAFETY_CAVEAT,
    }


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_risk_flags(
    note_parser_output: dict,
    temporal_output: dict,
    rag_output: dict,
    sofa_total: int,
    qsofa_total: int,
    trends: list[dict],
) -> list[dict]:
    """Build detailed risk flags by combining all agent outputs."""
    risk_flags: list[dict] = []

    # Collect conditions from note parser
    # note_parser_output may have structure: {"aggregated": {"all_conditions": [...]}}
    # or flat: {"all_conditions": [...]}
    conditions: set[str] = set()
    aggregated = note_parser_output.get("aggregated", {})
    all_conditions = aggregated.get("all_conditions", note_parser_output.get("all_conditions", []))
    if isinstance(all_conditions, list):
        for item in all_conditions:
            if isinstance(item, dict):
                conditions.add(item.get("condition", item.get("value", "")))
            elif isinstance(item, str):
                conditions.add(item)

    # Also check direct conditions if single-note output
    direct_conditions = note_parser_output.get("conditions", [])
    if isinstance(direct_conditions, list):
        for c in direct_conditions:
            conditions.add(c if isinstance(c, str) else str(c))

    # Check critical findings from aggregated
    critical_findings = aggregated.get("critical_findings", note_parser_output.get("critical_findings", []))
    for finding in critical_findings:
        if isinstance(finding, str) and finding:
            conditions.add(finding)

    conditions.discard("")

    # If no conditions were found but scores suggest sepsis, add it
    if not conditions and (sofa_total >= 2 or qsofa_total >= 2):
        conditions.add("Suspected Sepsis")

    # Build a risk flag per condition
    for condition in conditions:
        evidence: list[str] = []
        recommended_actions: list[str] = []
        guideline_citations: list[dict] = []

        # SOFA evidence
        if sofa_total >= 2:
            evidence.append(f"SOFA {sofa_total} (>= 2 threshold)")
        # qSOFA evidence
        if qsofa_total >= 2:
            evidence.append(f"qSOFA {qsofa_total}/3")

        # Lab trend evidence
        for t in trends:
            if t.get("is_concerning", False):
                vals = t.get("values", [])
                if vals:
                    last_val = vals[-1]
                    if isinstance(last_val, dict):
                        last_val = last_val.get("value", "?")
                    evidence.append(f"{t['lab_name']} {t['trend']} (latest: {last_val})")

        # RAG recommendations and citations
        # rag_output["recommendations"] may be a dict {"recommendations": [...], "evidence_summary": "..."}
        # or a list directly
        raw_recs = rag_output.get("recommendations", {})
        if isinstance(raw_recs, dict):
            rec_list = raw_recs.get("recommendations", [])
            if isinstance(rec_list, list):
                recommended_actions.extend(rec_list)
        elif isinstance(raw_recs, list):
            recommended_actions.extend(raw_recs)

        # rag_output["guidelines"] is a list of dicts, "citations" is a formatted string
        raw_guidelines = rag_output.get("guidelines", [])
        if isinstance(raw_guidelines, list):
            for g in raw_guidelines:
                if isinstance(g, dict):
                    guideline_citations.append({
                        "guideline_name": g.get("source", "Clinical Guideline"),
                        "text": g.get("text", "")[:200],
                        "relevance_score": g.get("relevance_score", 0),
                        "source_document": g.get("source", ""),
                    })

        # Condition-specific risk level
        condition_lower = condition.lower()
        if "sepsis" in condition_lower or "septic" in condition_lower:
            if sofa_total >= 10:
                condition_risk = "CRITICAL"
            elif sofa_total >= 6:
                condition_risk = "HIGH"
            elif sofa_total >= 2:
                condition_risk = "MODERATE"
            else:
                condition_risk = "LOW"
        else:
            condition_risk = determine_risk_level(sofa_total, qsofa_total, trends, 0)

        # Confidence estimate based on amount of evidence
        evidence_count = len(evidence) + len(guideline_citations)
        if evidence_count >= 5:
            confidence = 0.90
        elif evidence_count >= 3:
            confidence = 0.75
        elif evidence_count >= 1:
            confidence = 0.60
        else:
            confidence = 0.40

        risk_flags.append({
            "condition": condition,
            "risk_level": condition_risk,
            "evidence": evidence,
            "guideline_citations": guideline_citations,
            "recommended_actions": recommended_actions,
            "confidence": round(confidence, 2),
        })

    # Sort by risk level severity
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MODERATE": 2, "LOW": 3}
    risk_flags.sort(key=lambda f: severity_order.get(f["risk_level"], 4))

    return risk_flags


def _generate_executive_summary(
    patient_info: dict,
    risk_level: str,
    risk_flags: list[dict],
    sofa_total: int,
    qsofa_total: int,
    disease_progression: str,
) -> str:
    """Generate a 2-3 sentence executive summary using Gemini."""
    patient_id = patient_info.get("patient_id", "UNKNOWN")
    age = patient_info.get("age", "unknown")
    gender = patient_info.get("gender", "unknown")

    conditions = [f["condition"] for f in risk_flags]
    top_evidence = []
    for f in risk_flags[:3]:
        top_evidence.extend(f.get("evidence", [])[:2])

    prompt = f"""Write a concise 2-3 sentence executive clinical summary for an ICU patient.

Patient: {age}yo {gender} (ID: {patient_id})
Overall Risk Level: {risk_level}
Active Conditions: {', '.join(conditions) if conditions else 'None identified'}
SOFA Score: {sofa_total}/24
qSOFA Score: {qsofa_total}/3
Key Evidence: {'; '.join(top_evidence) if top_evidence else 'None'}
Disease Trajectory: {disease_progression[:200]}

Write a brief, precise clinical summary. No recommendations, just current status."""

    try:
        response = _model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(temperature=LLM_TEMPERATURE),
        )
        return response.text.strip()
    except Exception as exc:
        logger.warning("Gemini executive summary generation failed: %s", exc)

        # Fallback summary
        conditions_str = ", ".join(conditions) if conditions else "no specific conditions identified"
        return (
            f"Patient {patient_id} ({age}yo {gender}) is classified as {risk_level} risk. "
            f"SOFA score is {sofa_total}/24 and qSOFA is {qsofa_total}/3. "
            f"Active concerns include {conditions_str}."
        )


def _generate_handoff_narrative(
    patient_info: dict,
    risk_level: str,
    risk_flags: list[dict],
    disease_progression: str,
    sofa_score: dict,
) -> tuple[str, list[str]]:
    """Generate natural language patient summary and active problems for handoff."""
    patient_id = patient_info.get("patient_id", "UNKNOWN")
    age = patient_info.get("age", "unknown")
    gender = patient_info.get("gender", "unknown")
    admission_reason = patient_info.get("diagnosis", patient_info.get("admission_reason", "unknown"))

    conditions = [f["condition"] for f in risk_flags]
    sofa_total = sofa_score.get("total", 0) if isinstance(sofa_score, dict) else 0

    prompt = f"""Generate a shift handoff summary for an ICU patient.

Patient: {age}yo {gender} (ID: {patient_id})
Admission Reason: {admission_reason}
Risk Level: {risk_level}
SOFA: {sofa_total}
Active Conditions: {', '.join(conditions) if conditions else 'None identified'}
Disease Progression: {disease_progression[:300]}

Return as JSON:
{{
  "patient_summary": "1-2 sentence summary of current status",
  "active_problems": ["problem 1", "problem 2", ...]
}}

Only return valid JSON. No explanation."""

    try:
        response = _model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(temperature=LLM_TEMPERATURE),
        )
        result = response.text.strip()

        if result.startswith("```"):
            lines = result.split("\n")
            lines = [l for l in lines if not l.strip().startswith("```")]
            result = "\n".join(lines)

        parsed = json.loads(result)
        patient_summary = parsed.get("patient_summary", "")
        active_problems = parsed.get("active_problems", [])
        return patient_summary, active_problems

    except Exception as exc:
        logger.warning("Gemini handoff narrative failed: %s", exc)

        # Fallback
        patient_summary = (
            f"{age}yo {gender} admitted for {admission_reason}. "
            f"Currently {risk_level} risk with SOFA {sofa_total}."
        )
        active_problems = conditions if conditions else ["No specific conditions identified"]
        return patient_summary, active_problems


def _assess_data_completeness(
    labs_df: pd.DataFrame,
    vitals_df: pd.DataFrame,
    sofa_components: dict,
) -> dict:
    """Assess whether critical lab/vital data is available for reliable scoring.

    Checks for the presence of the 6 key SOFA organ-system parameters.
    If most are missing, the SOFA score is unreliable and should not be
    used to declare a patient LOW risk.

    Returns
    -------
    dict with is_incomplete, missing_critical, available_critical, completeness_pct.
    """
    # Critical parameters needed for reliable SOFA scoring
    critical_labs = ["Creatinine", "Bilirubin", "Platelets", "Lactate"]
    critical_vitals = ["GCS"]

    missing: list[str] = []
    available: list[str] = []

    # Check labs
    if labs_df is not None and not labs_df.empty:
        param_col = "parameter" if "parameter" in labs_df.columns else "label" if "label" in labs_df.columns else None
        if param_col:
            lab_params = labs_df[param_col].dropna().str.lower().unique().tolist()
            for lab in critical_labs:
                if any(lab.lower() in p for p in lab_params):
                    available.append(lab)
                else:
                    missing.append(lab)
        else:
            missing.extend(critical_labs)
    else:
        missing.extend(critical_labs)

    # Check vitals
    if vitals_df is not None and not vitals_df.empty:
        param_col = "parameter" if "parameter" in vitals_df.columns else None
        if param_col:
            vital_params = vitals_df[param_col].dropna().str.upper().unique().tolist()
            for vital in critical_vitals:
                if any(vital.upper() in p for p in vital_params):
                    available.append(vital)
                else:
                    missing.append(vital)
        else:
            missing.extend(critical_vitals)
    else:
        missing.extend(critical_vitals)

    total = len(critical_labs) + len(critical_vitals)
    completeness_pct = (len(available) / total * 100) if total > 0 else 0

    # Also check SOFA components — if most are 0, it could be missing data
    zero_components = sum(
        1 for v in sofa_components.values() if v == 0
    ) if sofa_components else 6
    all_zero = zero_components >= 5  # 5 or 6 out of 6 components are zero

    # Data is incomplete if >= 3 critical parameters are missing
    # OR if all SOFA components are zero AND at least 2 params are missing
    is_incomplete = (
        len(missing) >= 3
        or (all_zero and len(missing) >= 2)
    )

    return {
        "is_incomplete": is_incomplete,
        "missing_critical": missing,
        "available_critical": available,
        "completeness_pct": round(completeness_pct, 1),
        "zero_sofa_components": zero_components,
    }


def _check_prior_consistency(
    labs_df: pd.DataFrame,
    lab_name: str,
    window_days: int = 3,
) -> dict:
    """Check whether a lab's prior values over *window_days* are consistent.

    A lab series is considered "consistent" if the coefficient of variation
    (CV = std / mean) is below 0.25 (25%) across the lookback window,
    meaning the prior readings were relatively stable.

    Returns
    -------
    dict with keys: is_consistent, mean, std, cv, count.
    """
    if labs_df is None or labs_df.empty:
        return {"is_consistent": False, "mean": 0, "std": 0, "cv": 0, "count": 0}

    param_col = "label" if "label" in labs_df.columns else "parameter" if "parameter" in labs_df.columns else None
    value_col = "valuenum" if "valuenum" in labs_df.columns else "value" if "value" in labs_df.columns else None
    time_col = "charttime" if "charttime" in labs_df.columns else "timestamp" if "timestamp" in labs_df.columns else None

    if param_col is None or value_col is None:
        return {"is_consistent": False, "mean": 0, "std": 0, "cv": 0, "count": 0}

    param_data = labs_df.loc[
        labs_df[param_col].str.lower() == lab_name.lower()
    ].copy()
    param_data = param_data.dropna(subset=[value_col])

    if time_col and time_col in param_data.columns:
        param_data = param_data.sort_values(time_col)

    if len(param_data) < 4:
        # Need at least 4 readings (3 prior + 1 new) to assess consistency
        return {"is_consistent": False, "mean": 0, "std": 0, "cv": 0, "count": 0}

    # Exclude the latest value (the potentially anomalous one)
    prior_data = param_data.iloc[:-1]
    values = prior_data[value_col].astype(float).values

    mean_val = float(np.mean(values))
    std_val = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
    cv = abs(std_val / mean_val) if mean_val != 0 else 0.0

    return {
        "is_consistent": cv < 0.25,  # Less than 25% variation = consistent
        "mean": round(mean_val, 2),
        "std": round(std_val, 2),
        "cv": round(cv, 4),
        "count": len(values),
    }


def generate_family_summary(
    report: dict,
    patient_info: dict,
    regional_language: str = "Hindi",
) -> dict:
    """Generate a compassionate, jargon-free summary for the patient's family.

    Covers the last 12 hours and is translated into English and a regional language.

    Parameters
    ----------
    report : dict
        Output from ``synthesize_report``.
    patient_info : dict
        Patient demographics.
    regional_language : str
        Target regional language for translation (default: Hindi).

    Returns
    -------
    dict with english_summary, regional_summary, language, generated_at, safety_caveat.
    """
    patient_id = patient_info.get("patient_id", "UNKNOWN")
    age = patient_info.get("age", "unknown")
    gender = patient_info.get("gender", "unknown")
    diagnosis = patient_info.get("diagnosis", patient_info.get("admission_reason", "unknown"))

    risk_level = report.get("risk_level", "UNKNOWN")
    risk_flags = report.get("risk_flags", [])
    timeline = report.get("timeline", [])
    disease_progression = report.get("disease_progression", "")
    sofa_score = report.get("sofa_score", {})
    sofa_total = sofa_score.get("total", 0) if isinstance(sofa_score, dict) else 0
    outlier_flags = report.get("outlier_flags", [])
    diagnosis_hold = report.get("diagnosis_hold", False)
    diagnosis_hold_details = report.get("diagnosis_hold_details", [])

    # Gather recent changes (last 12 hours)
    recent_events: list[str] = []
    timeline_timestamps = [
        e["timestamp"] for e in timeline
        if isinstance(e.get("timestamp"), datetime)
    ]
    max_ts = max(timeline_timestamps) if timeline_timestamps else datetime.now()
    cutoff = max_ts - timedelta(hours=12)
    for event in timeline:
        ts = event.get("timestamp")
        if isinstance(ts, datetime) and ts >= cutoff:
            desc = event.get("description", "")
            if desc:
                recent_events.append(desc)

    conditions = [f.get("condition", "") for f in risk_flags if isinstance(f, dict)]

    is_english_only = regional_language.lower() == "english"

    # ------------------------------------------------------------------
    # STEP 1: Generate the English summary
    # ------------------------------------------------------------------
    english_prompt = f"""You are a compassionate hospital communication specialist. Write a summary
of this ICU patient's last 12 hours for their NON-MEDICAL family members.

RULES:
- Use simple, warm, empathetic language. No medical jargon.
- Explain any medical terms in plain language (e.g., "SOFA score" → "a score doctors use to check how well the body's organs are working")
- Be honest but reassuring where appropriate
- Include what the care team is doing and monitoring
- If there are lab errors flagged, explain simply that "one test result looked unusual, so the doctors are re-running that test to make sure"
- Keep it to 150-250 words
- Address it as if speaking directly to the family

Patient: {age}-year-old {gender}
Admitted for: {diagnosis}
Current Status: {risk_level} risk
Key Conditions: {', '.join(conditions) if conditions else 'Being monitored'}
Overall body organ score: {sofa_total}/24 (higher means more support needed)
Recent Events (last 12 hours): {'; '.join(recent_events[:8]) if recent_events else 'Stable monitoring continues'}
Disease Trajectory: {disease_progression[:300] if disease_progression else 'Being closely monitored'}
Lab concerns flagged: {'Yes - some test results are being re-verified' if outlier_flags else 'None'}
Diagnosis on hold for retest: {'Yes' if diagnosis_hold else 'No'}

Write ONLY the summary in English. No headings, no labels, just the compassionate summary text."""

    try:
        fresh_model = _get_fresh_model()
        response = fresh_model.generate_content(
            english_prompt,
            generation_config=genai.GenerationConfig(temperature=0.3),
        )
        english_summary = response.text.strip()

        # Clean up labels if LLM added them
        for prefix in ["ENGLISH:", "English:"]:
            if english_summary.startswith(prefix):
                english_summary = english_summary[len(prefix):].strip()

    except Exception as exc:
        logger.warning("Gemini English family summary failed: %s", exc)

        # Fallback: build a hardcoded compassionate summary
        status_phrase = {
            "CRITICAL": "in serious condition and receiving intensive care",
            "HIGH": "being closely watched by the medical team",
            "MODERATE": "stable but still needs careful monitoring",
            "LOW": "doing relatively well and being monitored",
        }.get(risk_level, "being cared for by the medical team")

        english_summary = (
            f"Dear Family,\n\n"
            f"Your loved one, a {age}-year-old {gender}, was admitted for {diagnosis}. "
            f"Over the last 12 hours, they have been {status_phrase}. "
            f"The doctors are using a scoring system to track how well the body's organs "
            f"are working — the current score is {sofa_total} out of 24. A lower score is better. "
        )
        if conditions:
            english_summary += (
                f"The main concerns right now are: {', '.join(conditions)}. "
            )
        if outlier_flags:
            english_summary += (
                "One of the recent test results looked unusual compared to earlier tests. "
                "The medical team is re-running that test to make sure the result is accurate "
                "before making any changes to the treatment plan. "
            )
        english_summary += (
            "The care team is monitoring everything closely and will keep you updated. "
            "Please don't hesitate to ask the nurse or doctor if you have questions."
        )

    # ------------------------------------------------------------------
    # STEP 2: Translate into the regional language (separate API call)
    # ------------------------------------------------------------------
    regional_summary = ""
    if not is_english_only:
        regional_summary = _translate_to_regional(english_summary, regional_language)

    return {
        "patient_id": patient_id,
        "english_summary": english_summary,
        "regional_summary": regional_summary,
        "regional_language": regional_language,
        "generated_at": datetime.now(),
        "risk_level": risk_level,
        "diagnosis_hold": diagnosis_hold,
        "diagnosis_hold_details": diagnosis_hold_details,
        "safety_caveat": _FAMILY_CAVEAT,
    }


def _get_fresh_model():
    """Get a Gemini model with the CURRENT API key from .env.

    This ensures the model uses the latest key even if .env was updated
    after the module was first imported.
    """
    import os
    from dotenv import load_dotenv
    load_dotenv(override=True)  # override=True forces reload from .env
    fresh_key = os.getenv("GEMINI_API_KEY", "")
    if fresh_key and fresh_key not in ("PASTE_YOUR_KEY_HERE", "your-gemini-api-key-here"):
        genai.configure(api_key=fresh_key)
    return genai.GenerativeModel(GEMINI_MODEL)


def _translate_to_regional(english_text: str, target_language: str) -> str:
    """Translate the English family summary into a regional language via Gemini.

    Uses a dedicated API call (not combined with generation) for reliability.
    Retries once with a simpler prompt if the first attempt fails.
    """
    model = _get_fresh_model()

    # Primary translation prompt
    translate_prompt = f"""Translate the following English text into {target_language}.

RULES:
- Use the native script of {target_language} (e.g., Devanagari for Hindi, Bengali script for Bengali, etc.)
- This is a compassionate family communication about a hospital patient
- Keep the same warm, simple tone
- Do NOT add any English text, labels, or explanations
- Do NOT add "Translation:" or "{target_language}:" labels
- Output ONLY the {target_language} translation, nothing else

English text to translate:
{english_text}"""

    try:
        response = model.generate_content(
            translate_prompt,
            generation_config=genai.GenerationConfig(temperature=0.2),
        )
        translated = response.text.strip()

        # Remove any labels the LLM might have added
        for prefix in [
            f"{target_language}:", f"{target_language.upper()}:",
            f"{target_language} Translation:", "Translation:",
            "Here is the translation:", "Here's the translation:",
        ]:
            if translated.startswith(prefix):
                translated = translated[len(prefix):].strip()

        if translated and len(translated) > 20:
            return translated

    except Exception as exc:
        logger.warning("Gemini translation to %s failed (attempt 1): %s", target_language, exc)

    # Retry with a simpler prompt
    simple_prompt = f"Translate to {target_language} (use native script, no English):\n\n{english_text}"
    try:
        response = model.generate_content(
            simple_prompt,
            generation_config=genai.GenerationConfig(temperature=0.1),
        )
        translated = response.text.strip()
        for prefix in [f"{target_language}:", f"{target_language.upper()}:", "Translation:"]:
            if translated.startswith(prefix):
                translated = translated[len(prefix):].strip()
        if translated and len(translated) > 20:
            return translated
    except Exception as exc:
        logger.warning("Gemini translation to %s failed (attempt 2): %s", target_language, exc)

    return f"[{target_language} translation could not be generated. Please ask a staff member for assistance.]"


def _build_sofa_trend_string(report: dict) -> str:
    """Build a human-readable SOFA trend string from the report's timeline scores."""
    timeline = report.get("timeline", [])
    sofa_events = [
        e for e in timeline
        if e.get("event_type") == "score" and e.get("category") == "SOFA"
    ]

    if not sofa_events:
        sofa_total = report.get("sofa_score", {}).get("total", 0)
        return f"Current SOFA: {sofa_total} (single timepoint)"

    # Sort by timestamp
    sofa_events.sort(
        key=lambda e: e["timestamp"] if isinstance(e.get("timestamp"), datetime) else datetime.min
    )

    values = [str(int(e.get("value", 0))) for e in sofa_events]
    trend_str = " -> ".join(values)

    # Calculate time span
    timestamps = [
        e["timestamp"] for e in sofa_events
        if isinstance(e.get("timestamp"), datetime)
    ]
    if len(timestamps) >= 2:
        span = timestamps[-1] - timestamps[0]
        hours = span.total_seconds() / 3600
        trend_direction = "worsening" if int(values[-1]) > int(values[0]) else \
                          "improving" if int(values[-1]) < int(values[0]) else "stable"
        trend_str += f" ({trend_direction} over {hours:.0f}hrs)"

    return trend_str
